### ISSUE TITLE
启动后打开网页访问/chart显示404   

### ISSUE THREAD

**Issue by bigKoki** [chinadx/chatgpt-web#1]
启动后打开网页访问/chart显示404   ，在controller里也收不到request， 请问是什么问题，谢谢作者分享

**Comment by chinadx** [comment]
/chat不是/chart

**Comment by bigKoki** [comment]
不好意思   昨天晚上发完问题就发现写错了  但是发送请求会超时   我是在自己电脑上挂的梯子   请问你是什么技术解决的呢

**Comment by chinadx** [comment]
恩。非常不幸的是。openai的api，在3月3号就被墙了。电脑挂梯子你看看你的web容器有没有走到梯子，走不到梯子的话还是没办法访问。
我是在amazon的aws申请了一个免费的境外服务器（新注册用户有1年的1核1G主机的免费使用期），挂上去能用。

**Comment by bigKoki** [comment]
我目前也准备搞一个aws的服务器   请问境外服务器搭建的web   国内访问会被墙吗

**Comment by chinadx** [comment]
不会被墙。aws你可以选首尔的节点，速度会快一些。

**Comment by bigKoki** [comment]
好的，非常感谢分享    ！！！！

**Comment by chinadx** [comment]
不客气，我刚更新了下代码，改成了GPT-3.5的接口了。

**Comment by bigKoki** [comment]
感谢  我国外服务器弄好了去试试

**Comment by bigKoki** [comment]
我想请问下作者  你readme里写的sessionToken是保持会话的意思吗  就是不能保持会话根据上下文提问是吧

**Comment by chinadx** [comment]
不是的。readme里面的sessionToken是github上其他工程师代码里面的chatgpt的鉴权方式。咱没用那个方式。

如果想要上下文关联的话，你参照gpt-3.5文档里面的，把上次问题和答案附加到request里面的messages数组里面就可以关联。我这里在message里面没有传，是因为想要节省一些调用token使用量。因为如果带上下文的话，每次会话的token消耗像滚雪球一样，比较贵。

**Comment by bigKoki** [comment]
感谢回答   我搞了一个国外的服务器准备晚上试试你的新代码    
另外方便加个扣扣吗   一起交流一下

**Comment by chinadx** [comment]
> 
可以

**Comment by bigKoki** [comment]
我的扣扣864546664，如果方便的话就加一下，谢谢！！
